version: '3'

services:
  api-fileManager:
    image: bitnami/postgresql
    ports: 
      - 5432:5432
    environment: 
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_database=file_manager